Repository shiftcommerce/reference-site, pull requests merged in 2019-06, with the labels that each got.

#6 Issue: Secure Trendy Website
  package.json
  packages/reference/.env.example
  packages/reference/cypress/integration/minibag.js
  packages/reference/cypress/support/commands/cart.js
  packages/reference/cypress/support/commands/checkout.js
  packages/reference/next.config.js
  packages/reference/package.json
  packages/reference/server/middleware/security-headers.js
  packages/reference/server/server.js
  packages/reference/spec/server/middleware/security-headers.spec.js
  packages/shift-next-routes/package.json
  packages/shift-next-routes/src/index.js
  packages/shift-next-routes/src/middleware/content-security-policy.js
  packages/shift-next-routes/src/middleware/feature-policy.js
  packages/shift-next-routes/src/middleware/http-security-headers.js
  packages/shift-next/README.md
  packages/shift-next/src/actions/api-actions.js
  packages/shift-next/src/actions/cart-actions.js
  packages/shift-next/src/lib/api-client.js
  packages/shift-next/src/pages/static-page.js
  yarn.lock
Labels: security

#23 Bump package versions
  packages/reference/package.json
  yarn.lock
Labels: security

#26 Issue: Migrate tests to trendy
  packages/reference/cypress/fixtures/cart/add-clock-computer-13.json
  packages/reference/cypress/fixtures/cart/add-clock-computer-15.json
  packages/reference/cypress/integration/account/addresses.js
  packages/reference/cypress/integration/account/details.js
  packages/reference/cypress/integration/account/forgotten-password.js
  packages/reference/cypress/integration/account/login.js
  packages/reference/cypress/integration/account/order-history.js
  packages/reference/cypress/integration/account/registration.js
  packages/reference/cypress/integration/checkout/paypal/end_to_end_order_placement_spec.js
  packages/reference/cypress/integration/checkout/paypal/payment_methods_page_spec.js
  packages/reference/cypress/integration/checkout/paypal/review_and_submit_page_spec.js
  packages/reference/cypress/integration/checkout/paypal/shipping_method_page_spec.js
  packages/reference/cypress/integration/checkout/stripe/stripe-checkout.js
  packages/reference/cypress/integration/minibag.js
  packages/reference/cypress/integration/product.js
  packages/reference/cypress/integration/search/category.js
  packages/reference/cypress/integration/search/clearing-filters.js
  packages/reference/cypress/integration/search/global.js
  packages/reference/cypress/integration/search/pagination.js
  packages/reference/cypress/integration/search/price-filter.js
  packages/reference/cypress/integration/search/rating-filter.js
  packages/reference/cypress/integration/search/sorting.js
  packages/reference/cypress/integration/static-pages.js
  packages/reference/cypress/support/commands/address-book.js
  packages/reference/cypress/support/commands/cart.js
  packages/reference/cypress/support/commands/category.js
  packages/reference/cypress/support/commands/checkout.js
  packages/reference/cypress/support/commands/empty-search.js
  packages/reference/cypress/support/commands/login.js
  packages/reference/cypress/support/commands/products.js
  packages/reference/cypress/support/global-stubs.js
  packages/reference/cypress/support/index.js
  packages/reference/cypress/support/screenshot-settings.js
Labels: enhancement

#39 make menu only ever load once
  lerna.json
  packages/reference/cypress/integration/search/price-filter.js
  packages/reference/package.json
  packages/shift-next-routes/package.json
  packages/shift-next/package.json
  packages/shift-next/src/actions/menu-actions.js
  packages/shift-next/src/lib/with-redux-store.js
  packages/shift-next/src/reducers/set-menu.js
  packages/shift-node-api/package.json
  packages/shift-react-components/package.json
  packages/shift-react-components/src/components/navigation/navbar.js
Labels: performance

#35 Issue: Mega Nav Caching
  lerna.json
  packages/reference/.env.example
  packages/reference/README.md
  packages/reference/docker-compose.yml
  packages/reference/package.json
  packages/shift-next-routes/package.json
  packages/shift-next-routes/src/express/menu-handler.js
  packages/shift-next-routes/src/lib/memcached-store.js
  packages/shift-next-routes/src/lib/menu-cache.js
  packages/shift-next-routes/test/express/menu-handler.test.js
  packages/shift-next-routes/test/lib/menu-cache.test.js
  packages/shift-next/package.json
  packages/shift-next/src/lib/with-redux-store.js
  packages/shift-node-api/package.json
  packages/shift-react-components/package.json
  yarn.lock
Labels: performance
